### PR TITLE
Change log rake task should not generate tag sections w/o commits

### PR DESCRIPTION
**Pull request by rgo**
It tries to fix the PR: https://github.com/whitequark/parser/pull/372

### CODE REVIEW

**Comment by whitequark** [comment]
Can you also regenerate the changelog so I see what the actual difference is?

**Comment by rgo** [comment]
Because it's big I uploaded it to gist: https://gist.github.com/rgo/7de4b499a7ca6f972eba93dbefd70d43

**Comment by whitequark** [comment]
No, I mean, regenerate the changelog and include it in the PR. `rake changelog` and then push.

**Comment by rgo** [comment]
Give some time because after regenerate changelog I've seen something wrong.

Tag 2.4.0.0 is  duplicated with different date:

screen shot 2017-10-25 at 11 04 58

**Comment by rgo** [comment]
I saw the problem.

[These lines of code](https://github.com/rgo/parser/blob/2155a543641045a2480e93a40d5f01b3b4509bdd/Rakefile#L102-L104)[1]:

```
...
      current_version = "#{$1} (#{date})" if version =~ /(v[\d\w.]+)/
      current_version = "v#{Parser::VERSION} (#{date})" \
        if version =~ /(^| |\/)#{Regexp.escape branch}$/
...
```

If version matches with version format sets `current_version` as it.
If version matches with branch name sets as version Parser::VERSION that right now is the same that the current one.

It makes a duplicated entry with the same version but different date as you can see in my previous comment.

If you like:

  -  I can leave it as is knowing why it happens
  - Add some text which indicate is not released yet like "v2.4.0.0 (2017-10-24) - Not released"
  - Remove version number and change "Not released (2017-10-24)"

What would you like? perhaps you have any other idea

[1] https://github.com/rgo/parser/blob/2155a543641045a2480e93a40d5f01b3b4509bdd/Rakefile#L102-L104

**Comment by whitequark** [comment]
Thanks for investigating!

> Remove version number and change "Not released (2017-10-24)"

This option sounds good.

**Comment by rgo** [comment]
When you do a new release check the changelog commit/file to ensure is right (I hope so).

**Pull request merged**
