### PR TITLE
Configure GitHub Actions

### PR DESCRIPTION
**Pull request by palkan**
See discussion in https://github.com/whitequark/parser/pull/731

### CODE REVIEW

**Comment by palkan** [comment]
@iliabylich Looks like you need to enable Actions for forks somewhere in the settings: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories

**Comment by iliabylich** [comment]
I don't see any options on the Actions tab. Also, what you said should be configured on the fork repo:

> Workflows don't run on forked repositories by default. You must enable GitHub Actions in the Actions tab of the forked repository

I guess I could try committing these changes manually to master. Are you ok with it?

Also, which config is used when someone submits a PR that changes a workflow config?

**Comment by palkan** [comment]
> I guess I could try committing these changes manually to master. Are you ok with it?

Sure. Try to open PR, usually that works when you're a collaborator.

> which config is used when someone submits a PR that changes a workflow config?

The one from the PR.

**Comment by iliabylich** [comment]
https://github.com/whitequark/parser/pull/734 doesn't trigger GH action. Let's just merge this PR then

**Pull request merged**
