### PR TITLE
+ ruby31.y: allow "command" syntax in endless method definition

### PR DESCRIPTION
**Pull request by koic**
Fixes https://github.com/whitequark/parser/issues/799.

### CODE REVIEW

**Comment by iliabylich** [comment]
@koic could you also backport tests for `command kRESCUE_MOD arg` cases please? I'm talking about [these guys](https://github.com/ruby/ruby/commit/31794d2e733e081e4e221f27aff6380393981681#diff-88c80426a639b67117eb2cb10026a95fd1982a22d399442d9303a330e537b34bR1473-R1474).

Also this new syntax is a pure hack, `def foo = bar baz` is a command assignment that is reduced in a different way 🔥

**Comment by koic** [comment]
Thank you for your review. I've added missing backporting tests.

**Review by iliabylich — APPROVED** [review]
👍

**Comment by iliabylich** [comment]
@koic thanks!

**Pull request merged**
