### PR TITLE
- Add :csend to Parser::Meta::NODE_TYPES

### PR DESCRIPTION
**Pull request by mbj**
Also fixes a duplicate `send` member.

### CODE REVIEW

**Comment by mbj** [comment]
@whitequark This passes all tests but changes the coverage as measured by simplecov. I've no idea on how to configure the coverage expectation, nor why this constant literal change triggers a metric difference at all.

**Comment by alexdowad** [comment]
> I've no idea on ... why this constant literal change triggers a metric difference at all.

Because Coveralls is junk?

**Comment by alexdowad** [comment]
Thank you for catching this!

**Comment by mbj** [comment]
> Because Coveralls is junk?

One possible cause is that the constant literal case increases the overall LOC, that gets measured against the explicit covered LOC. But this is not the case here.

**Comment by whitequark** [comment]
I don't really care about spurious Coveralls changes, they are primarily used to measure the coverage of grammars.

**Comment by mbj** [comment]
@whitequark Can we get a release with that one? It would fix a special case on my side.

**Comment by alexdowad** [comment]
> Can we get a release with that one? It would fix a special case on my side.

I would recommend we finish #249 as well -- better if it makes it into the next minor release.

**Comment by whitequark** [comment]
#249 is a lot of code I won't have time to review for a while.

**Comment by mbj** [comment]
> #249 is a lot of code I won't have time to review for a while.

Also #249 is not a semantic change. It should not block a fix release IMO.

**Comment by alexdowad** [comment]
> #249 is a lot of code I won't have time to review for a while.

Very well.

**Comment by mbj** [comment]
> Also #249 is not a semantic change. It should not block a fix release IMO.

Correction it is a semantic change. But not a bugfix.

**Comment by whitequark** [comment]
`2.3.0.2`

**Comment by mbj** [comment]
thx

**Pull request merged**
