### PR TITLE
* Current 2.3 point release became 2.3.2, at patchlevel 113 on 2016-0…

### PR DESCRIPTION
**Pull request by riddochc**
Ruby development continues apace...

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I can't find Ruby `2.3.2` yet
And I am getting warning `2.3.2-compliant syntax, but you are running 2.3.1.`
Can this be ignored?

**Comment by whitequark** [comment]
@PikachuEXE Sorry for the noise. I've reverted this PR and released Parser 2.3.1.4.

**Comment by riddochc** [comment]
That's just weird... I wonder why they haven't actually put the release up, it was tagged back in April:

https://github.com/ruby/ruby/commit/a77d77c6e7c9dd453791d497fe1a253165da3a2d

I should've checked that, sorry.

**Comment by riddochc** [comment]
...Apparently it wasn't tagged after all, just version.h was updated.  That could explain a bit.

**Pull request merged**
