### PR TITLE
Extracted 'relop' rule to simplify comparisons.

### LINKED ISSUE #379: ruby/ruby@c1c3d073
See the upstream commit https://github.com/ruby/ruby/commit/c1c3d07332d32f0981d6019c3f851e51739f0eb2.

### PR DESCRIPTION
**Pull request by iliabylich**
Closes #379, #380.

### CODE REVIEW

**Comment by whitequark** [comment]
I believe this will only be in 2.5 so you'll need to split off ruby25.y first. Look at the commit introducing ruby24.y to see how that is done.

**Comment by whitequark** [comment]
Also, commits starting with `*` get changelog entries, and these two don't, so I would use something like

    ruby25.y: extract rel_expr rule.

    This commit tracks upstream commits  ruby/ruby@c1c3d07 and ruby/ruby@4a375f3.

(Squash the two since it makes little sense to keep them separate.)

**Comment by iliabylich** [comment]
@whitequark Done.

**Comment by whitequark** [comment]
Thanks. Can you rebase?

**Comment by iliabylich** [comment]
@whitequark What do you mean? There's nothing to rebase. This branch has 3 commits on top of the latest master.

**Comment by whitequark** [comment]
I mean fold df3323c into bb5c54d to get clean history, so that bisecting would never have to skip a broken commit.

**Comment by iliabylich** [comment]
@whitequark Done

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
