### PR TITLE
Bump ruby versions to 2.5.5 and 2.6.2.

### PR DESCRIPTION
**Pull request by iliabylich**
Closes https://github.com/whitequark/parser/issues/561 and https://github.com/whitequark/parser/issues/562

### CODE REVIEW

**Comment by whitequark** [comment]
@iliabylich I think you should be able to release yourself now.

**Comment by iliabylich** [comment]
@whitequark Bump version (to `2.6.2.0` in our case) and `rake release`? Nothing special?

**Comment by whitequark** [comment]
Yep, just that.

**Comment by iliabylich** [comment]
Nope, still doesn't work:
```
Couldn't git push. `git push ' failed with the following output:

remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:whitequark/parser.git
 ! [remote rejected] master -> master (protected branch hook declined)
```

However I see an "Edit" icon on the top right corner of Readme. Weird. Could you push it yourself please?

**Comment by whitequark** [comment]
@iliabylich I removed branch protection. I trust you wouldn't screw things up. Other collaborators also seem fine and mostly inactive anyway.

**Comment by iliabylich** [comment]
These words make me nervous. Thanks and done, parser 2.6.2.0 has been released.

**Comment by whitequark** [comment]
@iliabylich I'd add you to repo owners (which lets you bypass protection with one additional click) but it looks like GitHub only has that feature for organizations now.

**Comment by Drenmi** [comment]
Thanks, @whitequark and @iliabylich. 🙇

**Pull request merged**
