### PR TITLE
Some tweaks

### PR DESCRIPTION
**Pull request by alexdowad**
Just picked everything which should be uncontroversial out of #249. Hopefully these can be merged more quickly.

### CODE REVIEW

**Comment by whitequark** [comment]
LGTM other than comments.

**Comment by alexdowad** [comment]
> LGTM other than comments.

Would you like more comments? Less comments? Different comments?

**Comment by whitequark** [comment]
I meant the comments I left on the PR.

**Comment by alexdowad** [comment]
OK, thanks.

**Pull request merged**
