### PR TITLE
* parser/current: update 2.4 branch to 2.4.1.

### PR DESCRIPTION
**Pull request by tagliala**

### CODE REVIEW

**Comment by whitequark** [comment]
This must wait until https://github.com/whitequark/parser/issues/336 is fixed.

**Comment by whitequark** [comment]
Also, https://github.com/whitequark/parser/issues/337.

**Comment by tagliala** [comment]
Looks like it was fixed on 2.4.1:

```rb
2.4.1 :005 >   foo :bar, {
2.4.1 :006 >       a: proc do
2.4.1 :007 >         end,
2.4.1 :008 >       b: proc do
2.4.1 :009 >         end
2.4.1 :010?>   }
 => [:bar, {:a=>#<Proc:0x007fa2a58dbc20@(irb):6>, :b=>#<Proc:0x007fa2a58dbbf8@(irb):8>}] 
```

```rb
2.4.0 :001 > def foo a, h
2.4.0 :002?>     [a, h]
2.4.0 :003?>   end
 => :foo 
2.4.0 :004 > 
2.4.0 :005 >   foo :bar, {
2.4.0 :006 >       a: proc do
2.4.0 :007 >         end,
2.4.0 :008 >       b: proc do
2.4.0 :009 >         end
2.4.0 :010?>   }
SyntaxError: (irb):8: syntax error, unexpected keyword_do_block, expecting '}'
  b: proc do
            ^
```

**Comment by whitequark** [comment]
Exactly. And it wasn't fixed in *parser* 2.4.1.

**Comment by Harakiri24** [comment]
any updates on this?

**Comment by whitequark** [comment]
No.

**Comment by sPaCeMoNk3yIam** [comment]
Why is this closed? I still get the error.

**Comment by whitequark** [comment]
@sPaCeMoNk3yIam Dupe of #346.

**Pull request closed without merging**
