### PR TITLE
Add "modernized" nodes support to Parser::AST::Processor.

### PR DESCRIPTION
**Pull request by iliabylich**

### CODE REVIEW

**Comment by iliabylich** [comment]
@whitequark Could you release it please?

**Comment by whitequark** [comment]
2.5.0.4

**Comment by bbatsov** [comment]
Why "modernized"?

**Comment by iliabylich** [comment]
@whitequark Thanks!
@bbatsov Because all these nodes can appear in the AST only after enabling `Parser::AST::Builder.modernize`.

**Comment by iliabylich** [comment]
@whitequark I don't see 2.5.0.4 on https://rubygems.org/gems/parser. Could you release it again please? 😄

**Comment by whitequark** [comment]
Done

**Pull request merged**
