### PR TITLE
Tweaking tweaking

### PR DESCRIPTION
**Pull request by alexdowad**

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks! I really value this work--most of the code you're fixing is the result of iterative approximation of MRI behavior and it really should be refactored, yet at the same time I'm so used to its quirks that I have not noticed that at all.

**Comment by alexdowad** [comment]
And thank you!

**Comment by troessner** [comment]
And thank you both :laughing: 
(Without `parser` `Reek` would be significantly harder to maintain since the alternatives are....dire)

**Comment by whitequark** [comment]
@troessner Did you port Reek to Parser sometime? I must have missed that

**Comment by troessner** [comment]
Yes, we switched 1.25 years ago.

**Comment by bbatsov** [comment]
Nice! Parser hegemony! :-)

**Pull request merged**
