### PR TITLE
2.3: optional superclass rule

### PR DESCRIPTION
**Pull request by cremno**
See https://github.com/ruby/ruby/commit/d311b7d0eb1e973c8d143f03e66ab72588f57a2a.

### CODE REVIEW

**Comment by whitequark** [comment]
Huh, can't believe I missed that.

**Comment by bbatsov** [comment]
So, now you can write code like `class C end`? I wonder how no one noticed this.

**Comment by whitequark** [comment]
I'm especially surprised, given that I'm subscribed to parse.y via RSS.

**Comment by whitequark** [comment]
@cremno Thank you for this high quality PR. (I think you might be the second person who actually read CONTRIBUTING.md.)

**Comment by whitequark** [comment]
Pushed 2.3.0.1

**Pull request merged**
