### PR TITLE
+ emit "endless method def" as `:def` node.

### PR DESCRIPTION
**Pull request by iliabylich**
(according to https://github.com/whitequark/parser/pull/676#issuecomment-650327931)

2.8.0-dev is not released, so I think we are free to change it.

### CODE REVIEW

**Comment by iliabylich** [comment]
@marcandre PTAL, for some reason GH doesn't allow me to request a review from you

**Comment by palkan** [comment]
@iliabylich I tried to migrate to this version and found that it doesn't work in a way we it was discussed: `node.loc.end.nil?` couldn't be used, since `Map::EndlessDefinition` has no `#end` method. Not sure what is a proper way to fix this: drop `EndlessDefinition` and add `assignment` to `Definition` or inherit `EndlessDefinition` from `Definition` or simply duplicate `attr_accessor :end`. @marcandre Thoughts?

**Comment by marcandre** [comment]
On Thu, Jul 2, 2020, 06:05 Vladimir Dementyev <notifications@github.com>
wrote:

> Drop EndlessDefinition and add assignment to Definition
>

Seems the most useful...

>

**Comment by marcandre** [comment]
> @iliabylich I tried to migrate to this version and found that it doesn't work in a way we it was discussed: `node.loc.end.nil?` couldn't be used, since `Map::EndlessDefinition` has no `#end` method. Not sure what is a proper way to fix this: drop `EndlessDefinition` and add `assignment` to `Definition` or inherit `EndlessDefinition` from `Definition` or simply duplicate `attr_accessor :end`. @marcandre Thoughts?

#718 should be a good solution

**Pull request merged**
