### PR TITLE
Add support for the safe navigation operator in RubyMotion

### PR DESCRIPTION
**Pull request by MarkVillacampa**

### CODE REVIEW

**Comment by whitequark** [comment]
Any reference for this? Is RubyMotion still evolving? Do they talk about their syntax anywhere?

**Comment by MarkVillacampa** [comment]
I work at RubyMotion :)

The reference is here: https://github.com/HipByte/RubyMotion/blob/master/NEWS#L415

**Comment by whitequark** [comment]
Ack. Please add a test for your change (or more specifically, add RubyMotion to the implementation list for the existing test for the safe navigation )

**Comment by MarkVillacampa** [comment]
Done! Let me know if any other changes are needed.

**Comment by whitequark** [comment]
Any other syntactic changes I should know about? Specifically Parser currently implements the RubyMotion grammar as of:

> Date: Mon, 08 Jun 2015 18:25:09 +0300

Any chance you can show me the git log since then?

**Comment by MarkVillacampa** [comment]
No other changes to the parser that affect syntax since that date, apart from the &. operator. I will make sure to open an issue/send a PR to Parser if we make any changes.

Thank you for merging!

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
