### PR TITLE
Fix example in TreeRewriter documentation

### PR DESCRIPTION
**Pull request by mvz**
The `#rewrite` method takes at least two arguments: A buffer and an AST.

### CODE REVIEW

**Comment by mvz** [comment]
I pushed a fix that should make the build pass but I can also open another pull request for that if you prefer.

**Comment by mvz** [comment]
Hm ... looks like the fix from #535 will be needed as well.

**Comment by mvz** [comment]
I cherry-picked the commit from #535 and now finally Travis is green.

**Comment by iliabylich** [comment]
@whitequark Can we merge it?

**Comment by iliabylich** [comment]
Thanks!

**Pull request merged**
