### PR TITLE
remove GHA, allow-failure is not currently supported

### PR DESCRIPTION
**Pull request by iliabylich**

### CODE REVIEW

**Comment by iliabylich** [comment]
@palkan ok, it seems to be working now

**Comment by palkan** [comment]
🎉

**Comment by iliabylich** [comment]
Interesting. GH actions doesn't support "allow_failure" option (here's a tracking issue - https://github.com/actions/toolkit/issues/399), and so if rubocop/master or ruby-head are broken we get failure for the whole PR.

I'm not sure if that's the right strategy. Many commits will be marked as red because atm rubocop does `require 'parser/ruby28'` that doesn't exist anymore. PR is marked as red and all commits in the history will be red too.

I don't see any options except removing `.github` directory and waiting for https://github.com/actions/toolkit/issues/399 to be resolved.

**Comment by iliabylich** [comment]
I've removed `.github` directory

<details>
  <summary>Latest .github/workflows/test.yml</summary>
  
```yml
name: Tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      TRUFFLERUBYOPT: "--engine.Mode=latency"
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.4.10", "2.5.8", "2.6.6", "2.7.1", "jruby-9.2", "truffleruby"]
        test_command: ["bundle exec rake test"]
        allow_failure: [false]
        include:
          - ruby: "head"
            test_command: "bundle exec rake test"
            allow_failure: true
          - ruby: "2.7.1"
            test_command: "./ci/run_rubocop_specs"
            allow_failure: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /home/runner/bundle
        key: bundle-${{ matrix.ruby }}-${{ hashFiles('../Gemfile') }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Ragel
      run: |
        sudo apt-get update
        sudo apt-get install ragel
    - name: Bundle install
      run: |
        bundle config path /home/runner/bundle
        bundle install
        bundle update
    - name: Run tests
      run: |
        ${{ matrix.test_command }}
```
</details>

**Pull request merged**
