### PR TITLE
- test_current.rb: 2.8 -> 3.0

### PR DESCRIPTION
**Pull request by palkan**
Follow-up for #729

### CODE REVIEW

**Review by koic — APPROVED** [review]
👍

**Comment by palkan** [comment]
@iliabylich Maybe, we shouldn't allow failures for ruby-head?

Another idea is to migrate to Github Actions and see separate statuses for different versions in PRs. And GA will likely be faster than Travis.

I have a working configuration [here](https://github.com/ruby-next/parser/tree/master/.github/workflows) which could be ported to this repo.

**Comment by iliabylich** [comment]
> Maybe, we shouldn't allow failures for ruby-head?

Development branch of any repo on GH can be broken anytime. It shouldn't block us.

> migrate to Github Actions and see separate statuses

I look at ruby-head/rubocop statuses only when I cut a release or if I feel that PR has some potentially breaking changes. Otherwise it's useless (again, because both can be broken)

> And GA will likely be faster than Travis

I think it's fast enough. truffleruby is slow, but MRI tests take 1.5 minutes to run. Is truffleruby faster on GH actions? 👍 if so

**Comment by palkan** [comment]
> Is truffleruby faster on GH actions? 

Looks like slow is not the only problem 😀 `Fatal error: java.lang.OutOfMemoryError` https://travis-ci.org/github/whitequark/parser/jobs/723110359

Currently, I do not test against Truffle. I will check.

**Comment by iliabylich** [comment]
I've restarted the job and now it's green (this is the 2nd failure that I've seen so far).

There are a few more changes that should be done, I'll make them in a separate PR.

Thanks, merging!

**Comment by palkan** [comment]
>  Is truffleruby faster on GH actions?

~7-8 minutes: https://github.com/ruby-next/parser/runs/1057046471

I will try to provide a PR a bit later.

**Comment by iliabylich** [comment]
Ok, let's try it. Do you want to send a PR?

**Comment by palkan** [comment]
> Do you want to send a PR?

Yeah, I will try to do that tomorrow.

**Pull request merged**
