### PR TITLE
Detect and warn about empty else

### PR DESCRIPTION
**Pull request by iliabylich**
`else_` is nil in `def m; else; end`, but `else_t` is there.

### CODE REVIEW

**Comment by whitequark** [comment]
What's the motivation here?

**Comment by iliabylich** [comment]
to warn/reject code like `def m; else; end` because it's invalid

**Comment by whitequark** [comment]
Ah, I misread the code.

**Comment by iliabylich** [comment]
well, let me describe it better: useless else (i.e. without `rescue`) gives a warning before 2.6 and an error after. But if it's empty we don't generated this warning/error. Checking for `else_t` works for both empty and non-empty else

**Pull request merged**
