### PR TITLE
Use optparse instead of slop

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Supersedes #178

### CODE REVIEW

**Comment by whitequark** [comment]
Have you tested it?
```
$ ./bin/ruby-parse 
/home/whitequark/Work/parser/lib/parser/runner/ruby_parse.rb:98:in `setup_option_parsing': wrong number of arguments (1 for 0) (ArgumentError)
        from /home/whitequark/Work/parser/lib/parser/runner.rb:15:in `block in initialize'
        from /opt/rubies/ruby-2.1.1/lib/ruby/2.1.0/optparse.rb:880:in `initialize'
        from /home/whitequark/Work/parser/lib/parser/runner.rb:15:in `new'
        from /home/whitequark/Work/parser/lib/parser/runner.rb:15:in `initialize'
        from /home/whitequark/Work/parser/lib/parser/runner.rb:11:in `new'
        from /home/whitequark/Work/parser/lib/parser/runner.rb:11:in `go'
        from ./bin/ruby-parse:6:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
No, sorry, it sould be fixed now.

**Comment by whitequark** [comment]
Thanks!

**Comment by deivid-rodriguez** [comment]
No problem!

**Pull request merged**
