### PR TITLE
Allow rescue/else/ensure inside do/end blocks. [Feature #12906]

### PR DESCRIPTION
**Pull request by iliabylich**
Closes https://github.com/whitequark/parser/issues/337

### CODE REVIEW

**Comment by iliabylich** [comment]
@whitequark Does it make sense to add more tests to cover cases with `else` and `ensure`?

**Comment by whitequark** [comment]
Not really, my general rule is one test per one codepath, and you're only changing one here.

**Comment by whitequark** [comment]
I see you're fixing the issues in the bugtracker. Please note that the condition for a Parser release is all relevant (as per GitHub issues and position in an upstream branch) commits being in master. Once those are done I will be glad to cut a release.

**Comment by iliabylich** [comment]
Could you please organize issues (maybe using tags) to clearly show which of them are required to release a new version (2.4/2.5)?

**Comment by whitequark** [comment]
Sure: https://github.com/whitequark/parser/issues?q=is%3Aissue+is%3Aopen+label%3Ablocking-2.4

Note that it is very easy to determine which branches/releases a commit is in, provided that it's old enough. Of course, the information from the Ruby bug tracker takes precedence here.
screenshot_20171113_170925

**Pull request merged**
